# Generated by Django 6.0.6 on 2026-06-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
