# Generated by Django 6.0.6 on 2026-06-09 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_readinggoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readinggoal',
            unique_together={('user', 'year')},
        ),
    ]
